### ISSUE TITLE
[Setting] 프로젝트 세팅

### ISSUE THREAD

**Issue by ckkim817** [SOPKATHON-iOS-TEAM4/SERVER#1]
## ⚙️ ISSUE

서버 레포 초기 세팅을 위해 프로젝트 세팅을 하기 위한 이슈입니다.

## 📄 To-Do

- [x] 이슈 템플릿 지정
- [x] PR 템플릿 지정
- [x] spring init
- [x] .gitignore 추가
- [x] 필요한 의존성 추가
- [x] Swagger 세팅
